name: Vercel Preview Deployment

on:
  pull_request:
    branches: dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: create vercel.json
        run: |
          touch vercel.json
          echo '
          {
            "rewrites": [
              {
                "source": "/api/:url*",
                "destination": "${{ secrets.API_BASE_URL }}/:url*"
              }
            ],
            "version": 2,
            "public": false,
            "github": {
              "enabled": false
            },
            "builds": [
              { "src": "{{Source for distribution}}", "use": "@vercel/static" }
            ]
          }
          ' >> vercel.json
      - uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-args: '--preview'
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID}}
          vercel-project-id: ${{ secrets.VERCE_PROJECT_ID}}
          github-comment: false
