name: Vercel Preview Deployment

on:
  pull_request:
    branches: dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: create vercel.json
        run: |
          touch vercel.json
          echo '
          {
            "rewrites": [
              {
                "source": "/api/:url*",
                "destination": "${{ secrets.API_BASE_URL }}/:url*"
              }
            ]
          }
          ' >> vercel.json
      - uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID}}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID}}
